repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: check-yaml
    - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      types_or: [python, jupyter]
    - id: ruff-format
      types_or: [python, jupyter]

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      args: ["--ignore=scripts/"]
      entry: python3 -m pytest -m "not integration_test"
      pass_filenames: false
      always_run: true

ci:
    autofix_commit_msg: |
        [pre-commit.ci] Add auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    submodules: false
