# @package _global_

stages:
  condition_filter:
    _target_: naturalv2.sources.reddit.RedditConditionFilter
    llm: ${sample_model}
    llm_max_concurrency: ${coalesce:sample_model.max_parallel_requests, sample_model.client_kwargs.default_max_parallel_requests, 10}
    reddit_rpm: 95 # QPM is 100 with OAuth and 10 without; 95 allows for some buffer
    subreddit_post_limit: 5
    subreddit_post_char_limit: 1000
  process_archive_dump:
    _target_: naturalv2.sources.reddit.RedditDumpProcessor
    archive_dir_or_paths: ??
    num_workers: null
    max_open_files: 1000
  treatment_synonyms:
    _target_: naturalv2.sources.stages.SynonymStage
    attribute: treatment
    llm: ${search_model}
    max_concurrent_workers: ${coalesce:search_model.max_parallel_requests, search_model.client_kwargs.default_max_parallel_requests, 10}
  curate:
    _target_: naturalv2.sources.reddit.RedditCurateStage
    num_workers: null
    batch_size: 16_384
