defaults:
  - pipeline: natural
  - user: ${oc.env:USER}
  - model@cheap_model: vllm_server
  - /model/providers@cheap_model.deployment_params.model_1: litellm_proxy
  - model@sample_model: vllm_server
  - /model/providers@sample_model.deployment_params.model_1: litellm_proxy
  - model@probs_model: vllm_server
  - /model/providers@probs_model.deployment_params.model_1: hosted_vllm
  - eval: experiment
  - source@reddit: reddit
  - source@pubmed: pubmed
  - estimator: natural_ipw
  - _self_

seed: 42
experiment_name: test
conditions:
  - Nervous System Diseases
sources:
  - reddit
  - pubmed
split: train
train_ratio: 0.6
save_path: ${user.save_path}
data_path: ${user.data_path}
date_time: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# configs for filter_curate pipleine
curate_max_concurrency: 10
filter_by_date: True

probs_model:
  completion_type: text
  temperature: 1.0
  max_tokens: 1
  prompt_logprobs: 0
  get_response: False
  local: False

pipeline_stages:
  - _target_: naturalv2.pipeline.sample_extraction.RelevanceFilterStage
    model_cfg: ${cheap_model}
    max_concurrent_workers: 8

  - _target_: naturalv2.pipeline.sample_extraction.TreatmentOutcomeFilterStage
    model_cfg: ${cheap_model}
    max_concurrent_workers: 8

  - _target_: naturalv2.pipeline.sample_extraction.KnownsStage
    model_cfg: ${sample_model}
    max_concurrent_workers: 8

  - _target_: naturalv2.pipeline.sample_extraction.ImputationsStage
    model_cfg: ${sample_model}
    max_concurrent_workers: 8

  - _target_: naturalv2.pipeline.conditional_extraction.InclusionProbStage
    model_cfg: ${probs_model}
    max_concurrent_workers: 8

  - _target_: naturalv2.pipeline.conditional_extraction.ConditionalExtractionStage
    model_cfg: ${probs_model}
    max_concurrent_workers: 8

use_imputed_nones: True
