defaults:
  - pipeline: natural
  - model@cheap_model: vllm_server
  - /model/providers@cheap_model.deployment_params.model_1: litellm_proxy
  - model@sample_model: vllm_server
  - /model/providers@sample_model.deployment_params.model_1: litellm_proxy
  - model@probs_model: vllm_server
  - /model/providers@probs_model.deployment_params.model_1: hosted_vllm
  - eval: experiment
  - source@reddit: reddit
  - source@pubmed: pubmed
  - estimator: natural_ipw
  - _self_

seed: 42
experiment_name: test
conditions:
  - Nervous System Diseases
sources:
  - reddit
  - pubmed
split: train
train_ratio: 0.6
save_path: ${oc.env:SAVE_PATH,./outputs}
data_path: ${oc.env:DATA_PATH,./data}
date_time: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# configs for filter_curate pipleine
curate_max_concurrency: 10
filter_by_date: True

condition_config:
  _target_: naturalv2.pipeline.curation.ConditionStage
  model_cfg: ${sample_model}
  source_name:
  max_concurrent_workers: ${curate_max_concurrency}

synonym_config:
  _target_: naturalv2.pipeline.curation.SynonymStage
  model_cfg: ${sample_model}
  source_name:
  attribute: "treatment"
  max_concurrent_workers: ${curate_max_concurrency}

# configs for estimate_ate pipeline
pipeline_max_concurrent_workers: 8

pipeline_stages:
  # - _target_: naturalv2.pipeline.sample_extraction.RelevanceFilterStage
  #   model_cfg: ${cheap_model}
  #   max_concurrent_workers: ${pipeline_max_concurrent_workers}

  - _target_: naturalv2.pipeline.sample_extraction.TreatmentOutcomeFilterStage
    model_cfg: ${cheap_model}
    max_concurrent_workers: ${pipeline_max_concurrent_workers}

  - _target_: naturalv2.pipeline.sample_extraction.KnownsStage
    model_cfg: ${sample_model}
    max_concurrent_workers: ${pipeline_max_concurrent_workers}

  - _target_: naturalv2.pipeline.sample_extraction.ImputationsStage
    model_cfg: ${sample_model}
    max_concurrent_workers: ${pipeline_max_concurrent_workers}

  # # Use this for NATURAL-MC
  # - _target_: naturalv2.pipeline.sample_extraction.SampleTYStage
  #   model_cfg: ${sample_model}
  #   max_concurrent_workers: ${pipeline_max_concurrent_workers}

  - _target_: naturalv2.pipeline.conditional_extraction.InclusionProbStage
    model_cfg: ${probs_model}
    length_norm: False
    max_concurrent_workers: ${pipeline_max_concurrent_workers}
    use_offline_inference: True

  - _target_: naturalv2.pipeline.conditional_extraction.ConditionalExtractionStage
    model_cfg: ${probs_model}
    length_norm: False
    max_concurrent_workers: ${pipeline_max_concurrent_workers}
    use_offline_inference: True

use_imputed_nones: True
use_inclusion_weights: True
