model: meta-llama/Llama-2-70b-chat-hf
download_dir: ${user.vllm_model_cache}
llm_path: ""
tokenizer_path: ""
temperature: 1
top_p: 1
max_seq_len: 8000
max_gen_len: 1
batch_size: 4
gpu_mem_util: 0.9
seed: ${seed}
system_prompt: ""
add_bos: False
length_norm: False
num_gpus:
